### ISSUE TITLE
"Has changed on disk" popup each time I create a PHP class

### ISSUE THREAD

**Issue by devnix** [underground-works/sublime-php-namespace-monkey#4]
When creating a class with this plugin enabled, it's filling it exactly how I needed to.

The only annoying thing I'm experiencing is this dialog:
![image](https://user-images.githubusercontent.com/1777519/94111964-0945f680-fe45-11ea-936b-18878abe0a58.png)

If I hit reload the file loads empty, so I have to cancel and save.

**Comment by itsgoingd** [comment]
Hey, what sublime version and platform are you using? That dialog style is not very familiar to me.

**Comment by devnix** [comment]
Sublime build 3211, Ubuntu 20.04, nothing special.

Now I've seen that it's not happening 100% of the time, but it's not very casual. It's happening to me very often.

**Comment by itsgoingd** [comment]
Unfortunately I don't have a Linux machine ready for testing, but a few more questions:

- How are you creating the files?
- What other packages have you got installed?
- If you have `atomic_save` enabled in preferences can you try turning it off?

**Comment by devnix** [comment]
> Unfortunately I don't have a Linux machine ready for testing, but a few more questions:
> 
> * How are you creating the files?
On file sidebar, left click, new file
> * What other packages have you got installed?
How I can get a list? I don't think I have anything that could conflict
> * If you have `atomic_save` enabled in preferences can you try turning it off?
It is disabled.

At the moment it's not happening, I think. Maybe I had to kill all sublime-text processes?
